cc_library(
    name = "generic-type",
    #    srcs = ["GenericType.cpp"],
    #    hdrs = ["GenericType.h"],
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    visibility = ["//component:__pkg__"],
)
